//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSiteLCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string Postcode { get; set; }
        public string StreetNo { get; set; }
        public string Appendix { get; set; }
        public int StudentId { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Student Student { get; set; }
    }
}
