//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapSiteLCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int MatriculationNo { get; set; }
        public string Prename { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public int ExaminationNo { get; set; }
        public byte Activ { get; set; }
        public Nullable<System.DateTime> Registrationdate { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
