//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentCourses = new HashSet<StudentCourse>();
        }
    
        public string Forename { get; set; }
        public string Surname { get; set; }
        public int Id { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
